[build-system]
requires = ["hatchling>=1.5.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "ivert"
dynamic = ["version"]
description = "The ICESat-2 Validation of Elevations Reporting Tool (IVERT)"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Michael MacFerrin", email = "michael.macferrin@colorado.edu"},
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["Geospatial"]
dependencies = [
    "click",
    "colorama; platform_system == 'Windows'",
    "dateparser",
    "geopandas",
    "h5py",
    "matplotlib",
    "netCDF4",
    "numexpr",
    "numpy",
    "pandas",
    "psutil",
    "pyproj",
    "rasterio",
    "scipy",
    "shapely",
    "six",
    "tables",
    "tabulate",
    "xarray",
    "fetchez",
    "globato",
    "transformez",
]

[project.urls]
Source = "https://github.com/continuous-dems/ivert"

[project.scripts]
ivert = "ivert.cli:ivert_cli"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.version]
path = "src/ivert/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/ivert"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN001",   # missing-type-function-argument
    "ANN201",   # missing-return-type-undocumented-public-function
    "ANN202",   # missing-return-type-private-function
    "ANN204",   # missing-return-type-special-method
    "ANN205",   # missing-return-type-static-method
    "ARG001",   # unused-function-argument
    "ARG002",   # unused-method-argument
    "B006",     # mutable-argument-default
    "B007",     # unused-loop-control-variable
    "B008",     # function-call-in-default-argument
    "B023",     # function-uses-loop-variable
    "B904",     # raise-without-from-inside-except
    "B905",     # zip-without-explicit-strict
    "BLE001",   # blind-except
    "C401",     # unnecessary-generator-set
    "C403",     # unnecessary-list-comprehension-set
    "C404",     # unnecessary-list-comprehension-dict
    "C414",     # unnecessary-double-cast-or-process
    "C901",     # complex-structure
    "D100",     # undocumented-public-module
    "D101",     # undocumented-public-class
    "D102",     # undocumented-public-method
    "D103",     # undocumented-public-function
    "D104",     # undocumented-public-package
    "D107",     # undocumented-public-init
    "D205",     # missing-blank-line-after-summary
    "D301",     # escape-sequence-in-docstring
    "D400",     # missing-trailing-period
    "D401",     # non-imperative-mood
    "D415",     # missing-terminal-punctuation
    "D417",     # undocumented-param
    "DTZ001",   # call-datetime-without-tzinfo
    "DTZ005",   # call-datetime-now-without-tzinfo
    "DTZ007",   # call-datetime-strptime-without-zone
    "E501",     # line-too-long
    "EM101",    # raw-string-in-exception
    "EM102",    # f-string-in-exception
    "ERA001",   # commented-out-code
    "EXE001",   # shebang-not-executable
    "FBT001",   # boolean-type-hint-positional-argument
    "FBT002",   # boolean-default-value-positional-argument
    "FBT003",   # boolean-positional-value-in-call
    "FIX002",   # line-contains-todo
    "FURB110",  # if-exp-instead-of-or-operator
    "ICN001",   # unconventional-import-alias
    "N801",     # invalid-class-name
    "N802",     # invalid-function-name
    "N803",     # invalid-argument-name
    "N806",     # non-lowercase-variable-in-function
    "PD002",    # pandas-use-of-inplace-argument
    "PD011",    # pandas-use-of-dot-values
    "PERF401",  # vmanual-list-comprehension
    "PLC0415",  # import-outside-top-level
    "PLR0912",  # too-many-branches
    "PLR0913",  # too-many-arguments
    "PLR0915",  # too-many-statements
    "PLR2004",  # magic-value-comparison
    "PLW0603",  # global-statement
    "PLW1510",  # subprocess-run-without-check
    "PLW2901",  # redefined-loop-name
    "PT018",    # pytest-composite-assertion
    "PTH100",   # os-path-abspath
    "PTH102",   # os-mkdir
    "PTH103",   # os-makedirs
    "PTH107",   # os-remove
    "PTH109",   # os-getcwd
    "PTH110",   # os-path-exists
    "PTH111",   # os-path-expanduser
    "PTH112",   # os-path-isdir
    "PTH113",   # os-path-isfile
    "PTH117",   # os-path-isabs
    "PTH118",   # os-path-join
    "PTH119",   # os-path-basename
    "PTH120",   # os-path-dirname
    "PTH122",   # os-path-splitext
    "PTH123",   # builtin-open
    "PTH202",   # os-path-getsize
    "PTH204",   # os-path-getmtime
    "PTH207",   # glob
    "PTH208",   # os-listdir
    "RET503",   # implicit-return
    "RET504",   # unnecessary-assign
    "RUF001",   # ambiguous-unicode-character-string
    "RUF002",   # ambiguous-unicode-character-docstring
    "RUF005",   # collection-literal-concatenation
    "RUF012",   # mutable-class-default
    "RUF013",   # implicit-optional
    "RUF015",   # unnecessary-iterable-allocation-for-first-element
    "RUF059",   # unused-unpacked-variable
    "S101",     # assert
    "S110",     # try-except-pass
    "S301",     # suspicious-pickle-usage
    "S603",     # subprocess-without-shell-equals-true
    "S605",     # start-process-with-a-shell
    "S607",     # start-process-with-partial-path
    "SIM102",   # collapsible-if
    "SIM105",   # suppressible-exception
    "SIM115",   # open-file-with-context-handler
    "SIM118",   # in-dict-keys
    "SIM212",   # if-expr-with-twisted-arms
    "SLF001",   # private-member-access
    "T201",     # print
    "TD002",    # missing-todo-author
    "TD003",    # missing-todo-link
    "TRY003",   # raise-vanilla-args
    "TRY004",   # type-check-without-type-error
    "TRY300",   # try-consider-else
    "UP030",    # format-literals
    "UP031",    # printf-string-formatting
]
