"""Transform 3D points between coordinate reference systems, horizontally and vertically.

Vertical datum shifts use grids generated by transformez and cached on disk.
"""

import logging
import math
from pathlib import Path

import numpy as np
import pyproj
import rasterio
import transformez

from ivert.utils import dem_geom

logger = logging.getLogger(__name__)

_GRID_RESOLUTION = "3s"  # ~90 m — appropriate resolution for datum shift grids

# Shift grids are generated over the requested region snapped outward to a multiple
# of this many degrees. The cache file name carries the snapped bounds, so the name
# describes exactly the extent the grid covers and any later request landing inside
# that box is genuinely covered by the cached file.
_GRID_SNAP_DEGREES = 0.1


def transform_points(
    x: list | tuple | np.ndarray,
    y: list | tuple | np.ndarray,
    z: list | tuple | np.ndarray,
    src_epsg: str | int,
    dst_epsg: str | int,
    src_region: list | tuple | np.ndarray | None = None,
    cache_dir: str | None = None,
) -> tuple:
    """Transform a set of 3D points from one coordinate reference system to another.

    Args:
        x: X-coordinates (longitude or easting).
        y: Y-coordinates (latitude or northing).
        z: Z-coordinates (elevation).
        src_epsg: Source CRS as an EPSG code (int or str) or compound string
            (e.g. "EPSG:4326+3855" for WGS84 horizontal + EGM2008 vertical). The
            vertical part may also be a transformez reference ID, as in
            "EPSG:4326+vdatum:mllw".
        dst_epsg: Destination CRS in the same formats as src_epsg.
        src_region: Bounding box [xmin, xmax, ymin, ymax] in the source CRS.
            If None, derived from the extents of the input points.
        cache_dir: Directory for caching downloaded datum grids and the
            generated vertical shift grids. Defaults to './transformez_cache'
            in the current working directory.

    Creates:
        Shift grid .tif files may be written to cache_dir. These are reused
        on subsequent calls covering the same datum pair and region.

    Raises:
        ValueError: If the vertical datum transformation cannot be built.

    Returns:
        A 3-tuple of (x, y, z) numpy arrays in the destination CRS.

    """
    src_horz, src_vert = dem_geom.split_srs_string(src_epsg)
    dst_horz, dst_vert = dem_geom.split_srs_string(dst_epsg)

    same_horz = (src_horz is None and dst_horz is None) or (
        src_horz is not None
        and dst_horz is not None
        and src_horz.is_exact_same(dst_horz)
    )
    if same_horz and src_vert == dst_vert:
        return x, y, z

    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)

    # Horizontal reprojection
    if (
        src_horz is not None
        and dst_horz is not None
        and not src_horz.is_exact_same(dst_horz)
    ):
        xformer = pyproj.Transformer.from_crs(src_horz, dst_horz, always_xy=True)
        trans_x, trans_y = xformer.transform(x, y)
    else:
        trans_x, trans_y = x.copy(), y.copy()

    # Vertical datum shift
    if src_vert is not None and dst_vert is not None and src_vert != dst_vert:
        trans_z = apply_vertical_transform(
            x,
            y,
            z,
            src_vert=src_vert,
            dst_vert=dst_vert,
            src_region=src_region,
            cache_dir=cache_dir,
        )
    else:
        trans_z = z.copy()

    return trans_x, trans_y, trans_z


def _snap_region_outward(
    region_bounds: list[float],
    snap: float = _GRID_SNAP_DEGREES,
) -> list[float]:
    """Expand [w, e, s, n] outward to the surrounding multiples of 'snap' degrees.

    Snapping makes the region a function of a coarse grid rather than of the exact
    input points, so runs over slightly different extents share one cached shift
    grid instead of colliding on a rounded file name while needing different areas.
    """
    w, e, s, n = region_bounds
    w_snap = math.floor(w / snap) * snap
    e_snap = math.ceil(e / snap) * snap
    s_snap = math.floor(s / snap) * snap
    n_snap = math.ceil(n / snap) * snap

    # A bound sitting exactly on a multiple can snap to itself on both sides (and
    # floating-point division makes that hard to predict), which would ask for a
    # zero-width or zero-height grid. Keep at least one snap unit in each dimension.
    if e_snap - w_snap < snap:
        e_snap = w_snap + snap
    if n_snap - s_snap < snap:
        n_snap = s_snap + snap

    return [w_snap, e_snap, s_snap, n_snap]


def _grid_covers_region(grid_fn: str, region_bounds: list[float], tol=1e-9) -> bool:
    """Return True if the raster at 'grid_fn' is readable and spans region_bounds."""
    w, e, s, n = region_bounds
    try:
        with rasterio.open(grid_fn) as src:
            bounds = src.bounds
    except (OSError, rasterio.errors.RasterioError):
        # Unreadable or truncated (e.g. an interrupted earlier run): treat as absent.
        return False

    return (
        (bounds.left <= w + tol)
        and (bounds.right >= e - tol)
        and (bounds.bottom <= s + tol)
        and (bounds.top >= n - tol)
    )


def apply_vertical_transform(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    src_vert: str,
    dst_vert: str,
    src_region: list | tuple | np.ndarray | None,
    cache_dir: str | None,
) -> np.ndarray:
    """Compute and apply a vertical datum shift to z via a cached transformez grid.

    'src_vert' and 'dst_vert' are vertical references as split_srs_string() returns
    them: a bare EPSG code ('5703') or a transformez reference ID ('vdatum:mllw').
    """
    from scipy.interpolate import RegularGridInterpolator

    if src_region is None:
        region_bounds = [float(x.min()), float(x.max()), float(y.min()), float(y.max())]
    else:
        region_bounds = [
            float(src_region[0]),
            float(src_region[1]),
            float(src_region[2]),
            float(src_region[3]),
        ]

    # Strings: the cache folder and the grid file are handed to transformez.
    _cache = str(cache_dir) if cache_dir else str(Path.cwd() / "transformez_cache")
    Path(_cache).mkdir(parents=True, exist_ok=True)

    # ':' is not a legal path character on Windows, so 'vdatum:mllw' becomes
    # 'vdatum_mllw' in the file name. EPSG codes keep the names earlier grids had.
    src_name = src_vert.replace(":", "_")
    dst_name = dst_vert.replace(":", "_")

    grid_region = _snap_region_outward(region_bounds)
    w, e, s, n = grid_region
    grid_fn = str(
        Path(_cache)
        / f"vshift_{src_name}_{dst_name}_{w:.1f}_{e:.1f}_{s:.1f}_{n:.1f}.tif",
    )

    # Never reuse a cached grid that does not actually span the points being
    # transformed. Grids written by earlier versions were named from bounds rounded
    # to 0.1 degrees but generated over the exact (smaller) region, so a later run
    # covering more ground would silently reuse one that fell short and leave the
    # uncovered points unconverted. Coverage is checked against the real data
    # region, not the snapped one, so a grid trimmed by a pixel of increment
    # rounding is still accepted.
    if Path(grid_fn).exists() and not _grid_covers_region(grid_fn, region_bounds):
        logger.info(
            "Cached shift grid %s does not cover the requested region; regenerating.",
            grid_fn,
        )
        Path(grid_fn).unlink()

    if not Path(grid_fn).exists():
        shift_array = transformez.generate_grid(
            region=grid_region,
            increment=_GRID_RESOLUTION,
            datum_in=src_vert,
            datum_out=dst_vert,
            cache_dir=_cache,
            out_fn=grid_fn,
            verbose=False,
        )
        if shift_array is None:
            msg = (
                f"Vertical transform failed: {src_vert} → {dst_vert} "
                f"over region {grid_region}."
            )
            raise ValueError(msg)

    with rasterio.open(grid_fn) as src:
        shift_data = src.read(1).astype(float)
        grid_bounds = src.bounds
        if src.nodata is not None:
            shift_data[np.isclose(shift_data, src.nodata, atol=1e-4)] = np.nan

    height, width = shift_data.shape
    lons = np.linspace(grid_bounds.left, grid_bounds.right, width)
    lats = np.linspace(grid_bounds.bottom, grid_bounds.top, height)

    # A point outside the grid must never come back as a 0.0 shift: an unconverted
    # height is indistinguishable from a legitimate zero separation, and silently
    # leaves those points wrong by the full datum offset (~24 m for NAVD88 on the
    # Oregon coast). Fail loudly instead. The coverage check above should make this
    # unreachable; it is the backstop if it ever is not.
    outside = (
        (x < grid_bounds.left)
        | (x > grid_bounds.right)
        | (y < grid_bounds.bottom)
        | (y > grid_bounds.top)
    )
    if outside.any():
        n_outside = int(np.count_nonzero(outside))
        msg = (
            f"Vertical transform failed: {n_outside:,} of {outside.size:,} points fall "
            f"outside the shift grid {grid_fn} "
            f"(grid covers {tuple(round(b, 6) for b in grid_bounds)}, points span "
            f"x [{float(x.min()):.6f}, {float(x.max()):.6f}], "
            f"y [{float(y.min()):.6f}, {float(y.max()):.6f}]). "
            "Delete that file and retry."
        )
        raise ValueError(msg)

    # rasterio stores rows top-to-bottom; flip to ascending-lat order for interpolator
    interp = RegularGridInterpolator(
        (lats, lons),
        shift_data[::-1, :],
        method="linear",
        bounds_error=False,
        fill_value=np.nan,
    )

    shifts = interp(np.column_stack([y, x]))

    # In-bounds NaNs mean the grid itself has nodata there (a genuine gap in the
    # datum model), not a caching problem. Those heights cannot be converted, so
    # they stay NaN and are dropped downstream rather than silently passed through.
    n_nan = int(np.count_nonzero(np.isnan(shifts)))
    if n_nan:
        logger.warning(
            "%d of %d points fall on nodata cells of shift grid %s; "
            "their transformed heights will be NaN.",
            n_nan,
            shifts.size,
            grid_fn,
        )

    return z + shifts
